import { terser } from 'rollup-plugin-terser';
import filesize from 'rollup-plugin-filesize';
import replace from '@rollup/plugin-replace';
import base from './rollup.config';

const properties = [
	// engine
	// 'getColorTransform',
	// 'getMatrix',
	// 'onCollision',
	// 'onUpdate',
	// 'radius',
	// 'alpha',
	// 'color',
	// 'weight',
	// 'body',
	// 'sound',
	// 'impulse',
	// 'rotation',
	// 'scale',
	// 'scaleX',
	// 'scaleY',
	// 'enabled',
	// 'time',
	// 'children',
	// 'transparent',
	// 'onTouchDown',
	// 'onTouchUp',
	// 'onTouchMove',
	// 'onKeyDown',
	// 'onKeyUp',
	// 'onClick',
	// 'getHeight',
	// 'getWidth',
	// 'onChange',
	// 'touchable',
	// 'pallete',
	// 'shape',
	// 'visible',
	// 'brightness',
	// 'tint',
	// 'sizeMax',
	// 'geometry',
	// 'animationPaused',
	// 'playAnimation',
	// 'transformedMatrix',
	// 'vertecies',
	// 'normals',

	// // game
	// 'animationWalk',
	// 'addUnit',
	// 'removeUnit',
	// 'addBullet',
	// 'removeBullet',
	// 'addObject',
	// 'removeObject',
	// 'getUnitCount',
	// 'distance',
	// 'settings',
	// 'weapons',
	// 'weapon',
	// 'points',
	// '_reactionTime',
	// '_time',
	// '_state',
	// 'update',
	// 'reaction',
	// 'speed',
	// 'speedX',
	// 'speedY',
	// 'actions',
	// 'transitions',
	// 'condition',
	// 'fsm',
	// 'health',
	// 'damage',
	// 'walkSpeed',
	// // 'start',
	// 'target',
	// 'getNearOpponent',
	// 'getAction',
	// 'calculateVolume',
	// 'camera',
	// 'setState',
	// 'frequency',
	// 'angle',
	// 'stepX',
	// 'stepY',
	// 'static',
	// 'addImpulse',
	// 'setActiveWeapon',
	// 'player',
	// 'direction',
	// 'moveJoystick',
	// 'attackJoystick',
	// 'attack',
	// 'gunButton',
	// 'rifleButton',
	// 'shotgunButton',
	// 'units',
	// 'count',
];

const regex = new RegExp(properties.join('|'));

export default {
	...base,
	plugins: [
		...base.plugins,
		terser({ }),
		// terser({ mangle: { properties: { builtins: true, regex } } }),
		// terser(),
		filesize(),
		replace({
			// 'const ': 'let ',
			// 'const{': 'let{',

			// // vertex shader
			// 'a_position': 'a',
			// 'a_normal': 'b',
			// 'a_texCoord': 'c',
			// 'u_world': 'd',
			// 'u_object': 'e',
			// 'u_worldViewProjection': 'f',
			// 'u_worldInverseTranspose': 'g',
			// 't_position': 'h',
			// 't_normal': 'i',
			// 'surfaceWorldPosition': 'j',

			// // fragment shader
			// 'v_surfaceToLight': 'k',
			// 'surfaceToLightDirection': 'l',
			// 'v_normal': 'm',
			// 'v_texCoord': 'n',
			// // 'u_color': 'o',
			// 'u_image': 'p',
			// 'lightValue': 'r',

			// // webgl constants
			// 'gl.VERTEX_SHADER': 35633,
			// 'gl.FRAGMENT_SHADER': 35632,
			// 'gl.TEXTURE_2D': 3553,
			// 'gl.TEXTURE_WRAP_S': 10242,
			// 'gl.TEXTURE_WRAP_T': 10243,
			// 'gl.CLAMP_TO_EDGE': 33071,
			// 'gl.NEAREST': 9728,
			// 'gl.UNSIGNED_BYTE': 5121,
			// 'gl.RGBA': 6408,
			// 'gl.TEXTURE_MIN_FILTER': 10241,
			// 'gl.TEXTURE_MAG_FILTER': 10240,
			// 'gl.ARRAY_BUFFER': 34962,
			// 'gl.STATIC_DRAW': 35044,
			// 'gl.COLOR_BUFFER_BIT': 16384,
			// 'gl.DEPTH_BUFFER_BIT': 256,
			// 'gl.CULL_FACE': 2884,
			// 'gl.DEPTH_TEST': 2929,
			// 'gl.TRIANGLES': 4,
		}),
	],
};
