export const topLayer = [
    'CAAAAAATAAAAAAK',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'H             I',
];