export const topLayer = [
    'CAAAAAAtAAAAAAK',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'D             E',
    'H             I',
];